package dpapukchiev.sevenwonderssimulation.cards;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum CardName {
    APOTEKE("Aphoteke"),
    AQUADUKT("Aquadukt"),
    ARZNEIAUSGABE("Arzneiausgabe"),
    AUSGRABUNGSTTATTE("Ausgrabungsttatte"),
    BADER("Bader"),
    BASAR("Basar"),
    BEFESTIGUNSANLAGE("Befestigunsanlage"),
    BIBLIOTHEK("Bibliothek"),
    BILDHAUEREI("Bildhauerei"),
    ERZBERGWERK("Erzbergwerk"),
    FORSTWIRTSCHAFT("Forstwirtschaft"),
    FORUM("Forum"),
    GERICHT("Gericht"),
    GIESSEREI("Giesserei"),
    GLASHUTTE("Glashutte"),
    HOLZPLATZ("Holzplatz"),
    KARAWANSEREI("Karawanserei"),
    KASERNE("Kaserne"),
    KONTOR_OST("Kontor Ost"),
    KONTOR_WEST("Kontor West"),
    LABORATORIUM("Laboratorium"),
    MARKT("Markt"),
    MAUERN("Mauern"),
    PFANDHOUSE("Pfandhouse"),
    PRESSE("Presse"),
    SAGEWERK("Sagewerk"),
    SCHIESSPLATZ("Schiessplatz"),
    SCHULE("Schule"),
    SKRIPTORIUM("Skriptorium"),
    STALLE("Stalle"),
    STATUE("Statue"),
    STEINBRUCH("Steinbruch"),
    TAVERNE("Taverne"),
    TEMPEL("Tempel"),
    THEATER("Theater"),
    TONGRUBE("Tongrube"),
    TRAININGSGELANDE("Trainingsgelande"),
    WACHTURM("Wachturm"),
    WALDHOLE("Waldhole"),
    WEBSTUHL("Webstuhl"),
    WEINBERG("Weinberg"),
    WERKSTAT("Werkstat"),
    ZIEGELBRENNERI("Ziegelbrenneri"),
    ZIEGELEI("Ziegelei"),
    BAUMSCHULE("Baumschule"),
    MINE("Mine"),
    ALTAR("Altar"),
    PANTHENON("Pantheon"),
    GARTEN("Garten"),
    RATHAUS("Rathaus"),
    PALAST("Palast"),
    HAFEN("Hafen"),
    LEUCHTTURM("Leuchtturm"),
    HANDELSKAMMER("Handelskammer"),
    VERTEIDIGUNGSANLAGE("Verteidigungsanlage"),
    ZIRKUS("Zirkus"),
    WAFFENLAGER("Waffenlager"),
    BELAGERUNGSMASCHINEN("Belagerungsmaschinen"),
    ARENA("Arena"),
    LOGE("Loge"),
    OBSERVATORIUM("Observatorium"),
    SENAT("Senat"),
    UNIVERSTAT("Universtat"),
    AKADEMIE("Akademie"),
    STUDIENZIMMER("Studienzimmer"),
    GILDE_DER_ARBEITER("Gilde der Arbeiter"),
    GILDE_DER_KUNSTLER("Gilde der Kunstler"),
    GILDE_DER_HANDELER("Gilde der Handler"),
    GILDE_DER_PHILOSOPHEN("Gilde der Philosophen"),
    GILDE_DER_SPIONE("Gilde der Spione"),
    GILDE_DER_STRATEGEN("Gilde der Strategen"),
    GILDE_DER_REEDER("Gilde der Reeder"),
    GILDE_DER_WISSENSCHAFTLER("Gilde der Wissenschaftler"),
    GILDE_DER_BEAMTEN("Gilde der Beamten"),
    GILDE_DER_BAUMEISTER("Gilde der Baumeister");

    private String displayName;
}
